services:
  private-website:
    image: saltwood233/private-website:dev
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
    env_file:
      - .env
    environment:
      - IS_IN_DOCKER=true
      - TZ=Asia/Shanghai
    networks:
      - internal_network
    ports:
      - "127.0.0.1:2500:2500"
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: private_website_db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal_network
    restart: unless-stopped
    # 仅在容器内网暴露 MySQL 服务
    ports:
      - "127.0.0.1:3306:3306"  # 暴露到宿主机端口 3306，可取消注释暴露到公网

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ./mysql_data
      o: bind

networks:
  internal_network:
    driver: bridge
