services:
  private-website:
    image: saltwood233/private-website
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
    env_file:
      - .env
    environment:
      - IS_IN_DOCKER=true
      - TZ=Asia/Shanghai
    network_mode: host
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'